name: Docker Image CI

on:
  push:
    branches: [ Alian416-patch-1 ]
  pull_request:
    branches: [ Alian416-patch-1 ]

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
